config/routes.rb
Rails.application.routes.draw do
  resources :static, only: [:new, :show]
  root 'static#index'
  resources :sectors
  resources :units
  resources :properties
  resources :admins
  resources :tenants
  get '/success', to: "tenants#success", as: "success"
  get '/properties/:id/sectors', to: 'sector#show'
  get '/sectors/:id/units', to: 'unit#show'
  get '/about', to: 'static#about'


  # get "/tenant_login", to: 'tenants#tenant_login'
  get "/login", to: "sessions#new", as: "login"
  post "/logout", to: 'sessions#destroy'
  get "/logout", to: 'sessions#destroy'

  post "/sessions", to: "sessions#create", as: "sessions"
  # get "/dashboard", to: 'tenants#dashboard'
  get "/admin-dashboard", to: 'admins#dashboard' #, as: "dashboard"
  get "/tenant-dashboard", to: 'tenants#dashboard'
  # get '/tenants/:id/dashboard', to: 'tenants#dashboard', as: 'tenants_dashboard'
  get "pay_rent", to: "tenants#pay_rent"

  get "/admins_redir_from_dash", to: "admins#redir_from_dash"

  # ICEBOXED
  # get "/admin_login", to: 'admins#admin_login'

  # get "/login", to: 'static#login', as: 'login'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tenant.rb
class Tenant < ApplicationRecord
  has_secure_password
  belongs_to :unit, optional: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true

  def fullname
    self.first_name + " " + self.last_name
  end

  def verify_unit
    if !self.unit_id.nil?
      return true
    else
      return false
    end
  end

  def sector
      Sector.try(:find, self.unit.sector_id)
  end

  def property
    Property.try(:find, self.unit.sector.property_id)
  end
end

app/controllers/tenants_controller.rb
class TenantsController < ApplicationController
  before_action :is_tenant_logged_in?, except: [:new, :create]
  before_action :fetch_tenant, only: [:show, :edit, :update, :destroy]
  def new
    @tenant = Tenant.new
  end

  def create
    @tenant = Tenant.create(tenant_params)
    if @tenant.valid?
      flash[:notice] = "Account Successfully Created"
      redirect_to login_path
    else
      flash[:errors] = @tenant.errors.full_messages#"Account must include a first and last name, email, and password; emails must be unique."
      redirect_to new_tenant_path
    end
  end

  def success
  end

  def pay_rent
    @tenant = Tenant.find(session[:tenant_id])

  end

  def show
    # flash[:notice] = "Account Updated"
  end

  def dashboard
    if tenant_logged_in?
      @tenant = Tenant.find(session[:tenant_id])
    else flash[:errors] = "You must be logged in to view the dashboard"
      redirect_to login_path
    end
  end

  def index
    @sectors = Sector.all.group_by{|sector| sector.property.name}
    @units = Unit.all.group_by{|unit| unit.sector.name}
    @tenants = Tenant.all.select{|tenant| tenant.verify_unit}
    @unassigned_tenants = Tenant.all - @tenants

    #.group_by{|tenant| tenant.unit}
  end

  def edit
    @tenant = Tenant.find(params[:id])
  end

  def update
    @tenant.update(tenant_params)
    if @tenant.valid?
      redirect_to @tenant
      flash[:notice] = "Account Updated"
    else
      flash[:errors] = @tenant.errors.full_messages #"Account must include a first and last name, email, and password."
      redirect_to edit_tenant_path(@tenant)
    end
  end

  def destroy
    @tenant.destroy
    flash[:notice] = "Account Deleted"
    redirect_to root_path
  end

  private
  def tenant_params
    params.require(:tenant).permit(:first_name, :last_name, :email, :password, :hint_password) #, :address_id, :contract_id
  end

  def is_tenant_logged_in?
    if !tenant_logged_in?
      flash[:errors]="Please login. Tenant access currently unavailable."
      redirect_to login_path
    end
  end

  def fetch_tenant
    @tenant = Tenant.find(params[:id])
  end

  def tenant_login_params
    params.require(:tenant).permit(:email, :password)
  end

end

app/helpers/tenants_helper.rb
module TenantsHelper
end

app/views/tenants/_form.html.erb
<%= form_for @tenant do |f|%>
<%= f.label :first_name%>
<%= f.text_field :first_name%><br>
<%= f.label :last_name%>
<%= f.text_field :last_name%><br>
<%= f.label :email%>
<%= f.text_field :email%><br>
<%= f.label :password%>
<%= f.password_field :password%><br>
<%= f.label :hint_password%>
<%= f.text_field :hint_password%><br>
<br>
<%= f.submit%>
<% end %>

app/views/tenants/_ledger.html.erb
<h2>Ledger</h2>

<table style="background-color:white;">
<tr>
  <th>Date</th>
  <th>Description</th>
  <th>Charge</th>
  <th>Payment</th>
</tr>
<tr>
  <td>5/01/18</td>
  <td>Deposit Charge</td>
  <td>($1000)</td>
  <td></td>
</tr>
<tr>
  <td>5/01/18</td>
  <td>1st Month Charge</td>
  <td>($1000)</td>
  <td></td>
</tr>
<tr>
  <td>5/01/18</td>
  <td>Last Month Charge</td>
  <td>($1000)</td>
  <td></td>
</tr>
<tr>
  <td>5/01/18</td>
  <td>Online Payment (Visa-0098)</td>
  <td></td>
  <td>$2000</td>
</tr>
<tr>
  <td>5/05/18</td>
  <td>Check Payment (Wells Fargo)</td>
  <td></td>
  <td>$1000</td>
</tr>
<tr>
  <td>5/15/18</td>
  <td>Rent Charge (June 2018)</td>
  <td>($1000)</td>
  <td></td>
</tr>
<tr>
  <td>5/15/18</td>
  <td>Water Charge (June 2018)</td>
  <td>($100)</td>
  <td></td>
</tr>
<tr>
  <td>5/15/18</td>
  <td>Utilties Charge (June 2018)</td>
  <td>($80)</td>
  <td></td>
</tr>
<tr>
  <td>5/15/18</td>
  <td>Parking Charge (June 2018)</td>
  <td>($100)</td>
  <td></td>
</tr>
<tr>
  <td>6/02/18</td>
  <td>Online Payment (MasterCard-0567)</td>
  <td></td>
  <td>$2280</td>
</tr>
<b>
<tr id="Balance">
  <td></td>
  <td>Balance</td>
  <td></td>
  <td>$0</td>
</tr>
</b>
</table>

app/views/tenants/_tenant_login_form.html.erb
<div class="container">

  <div class="omb_login">
    <h3 class="omb_authTitle"> Tenant Login
    </h3>
    <div class="row omb_row-sm-offset-3 omb_socialButtons">
      <div class="col-xs-4 col-sm-2">
        <a href="#" class="btn btn-lg btn-block omb_btn-facebook">
          <i class="fa fa-facebook visible-xs"></i>
          <span class="hidden-xs">Facebook</span>
        </a>
      </div>
      <div class="col-xs-4 col-sm-2">
        <a href="#" class="btn btn-lg btn-block omb_btn-twitter">
          <i class="fa fa-twitter visible-xs"></i>
          <span class="hidden-xs">Twitter</span>
        </a>
      </div>
      <div class="col-xs-4 col-sm-2">
        <a href="#" class="btn btn-lg btn-block omb_btn-google">
          <i class="fa fa-google-plus visible-xs"></i>
          <span class="hidden-xs">Google+</span>
        </a>
      </div>
    </div>
    <!-- Begin of logint page -->
    <div class="row omb_row-sm-offset-3 omb_loginOr">
      <div class="col-xs-12 col-sm-6">
        <hr class="omb_hrOr">
        <span class="omb_spanOr">or</span>
      </div>
    </div>

    <div class="row omb_row-sm-offset-3">
      <div class="col-xs-12 col-sm-6">
        <%= form_for @tenant, html: {:class => "omb_loginForm"} do |f| %>
        <div class="input-group">
          <span class="input-group-addon">
            <i class="fa fa-user"></i>
          </span>
          <%= f.text_field :email, name: "email", class: "form-control", :placeholder => "email address" %>
        </div>
        <span class="help-block"></span>

        <div class="input-group">
          <span class="input-group-addon">
            <i class="fa fa-lock"></i>
          </span>
          <%= f.password_field :password, name: "password", class: "form-control", placeholder: "Password" %>
        </div>
        <span class="help-block">Password error</span>
        <%= f.submit "Login", class: "btn btn-lg btn-primary btn-block" %>
      <% end  %>
    </div>
  </div>

  <div class="row omb_row-sm-offset-3">
    <div class="col-xs-12 col-sm-3">
      <label class="checkbox">
        <input type="checkbox" value="remember-me">Remember Me
      </label>
    </div>
    <div class="col-xs-12 col-sm-3">
      <p class="omb_forgotPwd">
        <a href="#">Forgot password?</a>
      </p>
    </div>
  </div>
</div>

</div>

app/views/tenants/_tenant_navigation.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top " role="navigation">
  <div class="container-fluid">
      <div class="navbar-header">

        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand navbar-nav" href="<%= root_path %>">Prop Pal (t_t)</a>
      </div>

      <div class="collapse navbar-collapse" id="myNavbar">

        <ul class="nav navbar-nav">
          <li class="active"><a href="<%= tenant_dashboard_path %>">Dashboard</a></li>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Pay Rent <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="<%= pay_rent_path %>">Make a Payment</a></li>
              <li><a href="#">Pay Portion</a></li>
              <li><a href="#">Pay Utilites</a></li>
            </ul>
          </li>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Jump To
              <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li> <%=link_to "Properties", properties_path%></li>
              <li> <%=link_to "Sectors", sectors_path%></li>
              <li> <%=link_to "Units", units_path%> </li>
            </ul>
          </li>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Contact PM <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">Unit Issue</a></li>
              <li><a href="#">Questions</a></li>
              <li><a href="#">Complaint</a></li>
              <li><a href="#">PM Contact Info</a></li>

            </ul>
          </li>
               <li><a href="#">Lease</a></li>
            </ul>


      <ul class="nav navbar-nav navbar-right">
        <li><a href="<%= tenant_path(@tenant) %>"><span class="glyphicon glyphicon-user"></span> Profile</a></li>
        <li>
          <% if tenant_logged_in? %>

            <a href="<%= logout_path %>"><span class="glyphicon glyphicon-log-out"></span> Logout </a>

          <% else %>
            <a href="<%= login_path %>"><span class="glyphicon glyphicon-log-in"></span> Login1 </a>
          <% end %></li>
      </ul>
    </div>
  </div>

</nav>

app/views/tenants/dashboard.html.erb
<%= render "tenant_navigation" %>
<br><br><br>
<h1> Welcome <%= @tenant.first_name %> </h1>

<br><br>
<%if @tenant.verify_unit%>
    <h3>Property info: </h3>
    <ul>
        <li><%=link_to @tenant.property.name, @tenant.property %></li>
    </ul>
    <h3>Sector/Unit info</h3>
    <ul>
        <li>Sector: <%= link_to @tenant.sector.name, @tenant.sector %></li>
        <li>Unit: <%= link_to @tenant.unit.name, @tenant.unit %></li>
    </ul>
<%else%>
<h3>You have not moved into a Unit yet.</h3>
<%end%>
<br><br>
<h3>Message board/ bulletin</h3>
<br><br>

app/views/tenants/edit.html.erb
<%if @admin%>
    <%= render '/partials/admin_navigation' %>
<%elsif @tenant %>
    <%= render '/tenants/tenant_navigation'%>
<%else%>
    <%= render '/partials/navigation'%>
<%end%>

<h1> Edit your profile </h1>

<% if flash[:errors] %>
  <div style="text-align:center;"class="errors"><h2><% flash[:errors].each do |er| %>
    <%= er %></h2></div>
    <% end %>
<% end %>

<%= render 'form' %>
<br><br>

app/views/tenants/index.html.erb
<h1>All Tenants</h1>
<ul>
<% @tenants.each do |tenant| %>
<li><%= link_to tenant.fullname, tenant %></li>
<% end %>
</ul>

  <% @sectors.each do |prop_name, sector_arr| %>
    <% if Property.where(name: prop_name).any? %>
      <h5>Property: <%= link_to prop_name, Property.where(name: prop_name).first %></h5>
      <ul>
      <%sector_arr.each do |sector|%>
        <% if Sector.find(sector.id) %>
          <h5>Sector: <%= link_to sector.name, sector %></h5>
          <ul>
            <%units = sector.units%>
            <%units.each do |unit|%>
              <li>Unit: <%=link_to unit.name, unit%></li>
                <%@tenants%>
            <%end%>
          </ul>
        <% end %>
      <% end %>
      </ul>
    <%end%>
  <%end%>

app/views/tenants/new.html.erb
<%if admin_logged_in?%>
    <%= render '/partials/admin_navigation' %>
<%elsif tenant_logged_in? %>
    <%= render '/tenants/tenant_navigation'%>
<%else%>
    <%= render '/partials/navigation'%>
<%end%>

<h1> Create a new account </h1>

  <% if flash[:errors] %>
    <div style="text-align:center;"class="errors"><h2>
      <% flash[:errors].each do |error| %>
        <%= error %>
      <% end %></h2></div>
  <% end %>

<%= render 'form'%>

app/views/tenants/pay_rent.html.erb
<h1>Rent Portal</h1>




<h3>Credit Card</h3>

<h3>Debit Card</h3>

<h3>PayPal</h3>

app/views/tenants/show.html.erb
<%if @admin%>
    <%= render '/partials/admin_navigation' %>
<%elsif @tenant %>
    <%= render '/tenants/tenant_navigation'%>
<%else%>
    <%= render '/partials/navigation'%>
<%end%>
<br>
<h1><%= @tenant.fullname %></h1>

<% if flash[:notice] %>
  <div style="text-align:center;"class="notice"><h2><%= flash[:notice] %></h2></div>
  <% end %>
<br>
<h2>Email: <%= @tenant.email %><br></h2>
<h3>Lease Number: <%= @tenant.contract_id %><br></h3>
<h3>Unit Number: <%= @tenant.unit_id %></h3>
<br><br>
<%= button_to "Edit", edit_tenant_path, method: "get" %> <br>

app/views/tenants/success.html.erb
<%if @admin%>
    <%= render '/partials/admin_navigation' %>
<%elsif @tenant %>
    <%= render '/tenants/tenant_navigation'%>
<%else%>
    <%= render '/partials/navigation'%>
<%end%>

<h1>Account Successfully Created</h1>
<h2>Redirecting you to the Login Page</h2>

app/views/tenants/tenant_login.html.erb
<%if @admin%>
    <%= render '/partials/admin_navigation' %>
<%elsif @tenant %>
    <%= render '/tenants/tenant_navigation'%>
<%else%>
    <%= render '/partials/navigation'%>
<%end%>

<%= render "tenant_login_form" %>