config/routes.rb
Rails.application.routes.draw do
  resources :static, only: [:new, :show]
  root 'static#index'
  resources :sectors
  resources :units
  resources :properties
  resources :admins
  resources :tenants
  get '/success', to: "tenants#success", as: "success"
  get '/properties/:id/sectors', to: 'sector#show'
  get '/sectors/:id/units', to: 'unit#show'
  get '/about', to: 'static#about'


  # get "/tenant_login", to: 'tenants#tenant_login'
  get "/login", to: "sessions#new", as: "login"
  post "/logout", to: 'sessions#destroy'
  get "/logout", to: 'sessions#destroy'

  post "/sessions", to: "sessions#create", as: "sessions"
  # get "/dashboard", to: 'tenants#dashboard'
  get "/admin-dashboard", to: 'admins#dashboard' #, as: "dashboard"
  get "/tenant-dashboard", to: 'tenants#dashboard'
  # get '/tenants/:id/dashboard', to: 'tenants#dashboard', as: 'tenants_dashboard'
  get "pay_rent", to: "tenants#pay_rent"

  get "/admins_redir_from_dash", to: "admins#redir_from_dash"

  # ICEBOXED
  # get "/admin_login", to: 'admins#admin_login'

  # get "/login", to: 'static#login', as: 'login'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admins/_admin_login_form.html.erb
<div class="container">

  <div class="omb_login">
    <h3 class="omb_authTitle">Administrator Login
    </h3>
    <div class="row omb_row-sm-offset-3 omb_socialButtons">
      <div class="col-xs-4 col-sm-2">
        <a href="#" class="btn btn-lg btn-block omb_btn-facebook">
          <i class="fa fa-facebook visible-xs"></i>
          <span class="hidden-xs">Facebook</span>
        </a>
      </div>
      <div class="col-xs-4 col-sm-2">
        <a href="#" class="btn btn-lg btn-block omb_btn-twitter">
          <i class="fa fa-twitter visible-xs"></i>
          <span class="hidden-xs">Twitter</span>
        </a>
      </div>
      <div class="col-xs-4 col-sm-2">
        <a href="#" class="btn btn-lg btn-block omb_btn-google">
          <i class="fa fa-google-plus visible-xs"></i>
          <span class="hidden-xs">Google+</span>
        </a>
      </div>
    </div>
    <!-- Begin of logint page -->
    <div class="row omb_row-sm-offset-3 omb_loginOr">
      <div class="col-xs-12 col-sm-6">
        <hr class="omb_hrOr">
        <span class="omb_spanOr">or</span>
      </div>
    </div>

    <div class="row omb_row-sm-offset-3">
      <div class="col-xs-12 col-sm-6">
        <%= form_for @admin, html: {:class => "omb_loginForm"} do |f| %>
        <div class="input-group">
          <span class="input-group-addon">
            <i class="fa fa-user"></i>
          </span>
          <%= f.text_field :email, name: "email", class: "form-control", :placeholder => "email address" %>
        </div>
        <span class="help-block"></span>

        <div class="input-group">
          <span class="input-group-addon">
            <i class="fa fa-lock"></i>
          </span>
          <%= f.password_field :password, name: "password", class: "form-control", placeholder: "Password" %>
        </div>
        <span class="help-block">Password error</span>
        <%= f.submit "Login", class: "btn btn-lg btn-primary btn-block" %>
      <% end  %>
    </div>
  </div>

  <div class="row omb_row-sm-offset-3">
    <div class="col-xs-12 col-sm-3">
      <label class="checkbox">
        <input type="checkbox" value="remember-me">Remember Me
      </label>
    </div>
    <div class="col-xs-12 col-sm-3">
      <p class="omb_forgotPwd">
        <a href="#">Forgot password?</a>
      </p>
    </div>
  </div>
</div>

</div>

app/views/admins/_form.html.erb
<%= form_for @admin do |f|%>
<%= f.label :first_name%>
<%= f.text_field :first_name%><br>
<%= f.label :last_name%>
<%= f.text_field :last_name%>
<br>
<%= f.label "Email: "%>
<%= f.text_field :email%><br>
<%= f.label :password%>
<%= f.password_field :password%><br>
<%= f.label :hint_password%>
<%= f.text_field :hint_password%><br>
<br><br>
<%= f.submit %>
<br><br>
<%end%>

app/views/admins/admin_login.html.erb
<%= render "/partials/admin_navigation" %>

<%= render "admin_login_form" %>

app/views/admins/dashboard.html.erb
<!-- #navigation partial is within admins directory -->
<%= render "/partials/admin_navigation" %>
<br>
<h1>Welcome to the Dashboard <%=current_admin.fullname%></h1>

<% if flash[:notice] %>
  <div style="text-align:center;"class="notice"><h2><%= flash[:notice] %></h2></div>
  <% end %>
<% if flash[:errors] %>
  <div style="text-align:center;"class="notice"><h2><%= flash[:errors] %></h2></div>
  <% end %>

<br><br>
<div class="col-md-6 col-sm-12 col-lg-6 col-xs-12">

  <img id="pie" src="<%=Gchart.pie(:data => [@empty_units.length, @full_units.length], :size => '250x300', :title => 'Current vacancies', :legend => @legend)%>" align="left"/>


</div>
<div class="col-sm-12 col-md-6 col-xs-12 col-lg-6">

  <h4>Take me to: </h4>
  <%= form_tag("/admins_redir_from_dash", method: "get") do %>
    Select Property: <%= collection_select :property, :property_id, @properties, :id, :name, {:prompt => 'Property'} %>
    <%= submit_tag("Go to Property") %>
  <% end %>
  <br>
  <%= form_tag("/admins_redir_from_dash", method: "get") do %>
    Select Sector:   <%= collection_select :sector, :sector_id, @sectors, :id, :prop_and_sector, {:prompt => 'Property|Sector'} %>
    <%= submit_tag("Go to Sector") %>
  <% end %>
  <br>
  <%= form_tag("/admins_redir_from_dash", method: "get") do %>
    Select Unit:     <%= collection_select :unit, :unit_id, @units, :id, :prop_sect_unit, {:prompt => 'Property|Sector|Unit'} %>
    <%= submit_tag("Go to Unit") %>
  <% end %>
</div>



<% link_to 'Show Property', @property  %>

app/views/admins/edit.html.erb
<%= render "partials/admin_navigation" %>

<h1> Edit your profile </h1>
<br>
<%= render 'form' %>

<br>
<%= button_to "Delete account", @admin, method: "delete"%>

app/views/admins/index.html.erb
<%= render "/partials/admin_navigation" %>

<h1>admin index page</h1>
<% @admins.each do |admin| %>
<%= link_to admin.fullname, admin %>
<% end %>

app/views/admins/new.html.erb
<h1> Create new Admin account </h1>

<%= render 'form'%>

app/views/admins/show.html.erb
<%= render "/partials/admin_navigation" %>
<br><br>
<h1><%= "Welcome, #{@admin.fullname}" %></h1>

<br>
<h2>Email: <%= @admin.email%></h2>
<br>

<%= button_to "Edit", edit_admin_path, method: "get"%>
<br><br>

<h2>Current Portfolio: </h2>
<% @admin.properties.each do |property| %>
<h3><%= link_to property.name, property %></h3>
<% end %>