config/routes.rb
Rails.application.routes.draw do
  resources :static, only: [:new, :show]
  root 'static#index'
  resources :sectors
  resources :units
  resources :properties
  resources :admins
  resources :tenants
  get '/success', to: "tenants#success", as: "success"
  get '/properties/:id/sectors', to: 'sector#show'
  get '/sectors/:id/units', to: 'unit#show'
  get '/about', to: 'static#about'


  # get "/tenant_login", to: 'tenants#tenant_login'
  get "/login", to: "sessions#new", as: "login"
  post "/logout", to: 'sessions#destroy'
  get "/logout", to: 'sessions#destroy'

  post "/sessions", to: "sessions#create", as: "sessions"
  # get "/dashboard", to: 'tenants#dashboard'
  get "/admin-dashboard", to: 'admins#dashboard' #, as: "dashboard"
  get "/tenant-dashboard", to: 'tenants#dashboard'
  # get '/tenants/:id/dashboard', to: 'tenants#dashboard', as: 'tenants_dashboard'
  get "pay_rent", to: "tenants#pay_rent"

  get "/admins_redir_from_dash", to: "admins#redir_from_dash"

  # ICEBOXED
  # get "/admin_login", to: 'admins#admin_login'

  # get "/login", to: 'static#login', as: 'login'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/partials/_admin_navigation.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top " role="navigation">
  <div class="container-fluid">
      <div class="navbar-header">

        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand navbar-nav" href="<%= root_path %>">Prop Pal (a_a)</a>
      </div>

      <div class="collapse navbar-collapse" id="myNavbar">

        <ul class="nav navbar-nav">
          <li class="active"><a href="<%= admin_dashboard_path %>">Dashboard</a></li>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Properties <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li> <%=link_to "Properties", properties_path%></li>
              <li> <%=link_to "Sectors", sectors_path%></li>
              <li> <%=link_to "Units", units_path%> </li>
            </ul>
          </li>
          
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Contracts <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">New Lease</a></li>
              <li><a href="#">Add Lessee</a></li>
              <li><a href="#">Amend Lease</a></li>
            </ul>
          </li>
              <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">Applicants <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="#">New Application</a></li>
                  <li><a href="#">Review Applicants</a></li>
                  <li><a href="#">Other</a></li>
                </ul>
              </li>
            </ul>


      <ul class="nav navbar-nav navbar-right">
        <li><a href="<%= admin_path(@admin) %>"><span class="glyphicon glyphicon-user"></span> Profile</a></li>
        <li>
          <% if admin_logged_in? %>

            <a href="<%= logout_path %>"><span class="glyphicon glyphicon-log-out"></span> Logout </a>

          <% else %>
            <a href="<%= login_path %>"><span class="glyphicon glyphicon-log-in"></span> Login </a>
          <% end %></li>
      </ul>
    </div>
  </div>

</nav>

app/views/partials/_login_form.html.erb
<div class="container">

  <div class="omb_login">
    <h3 class="omb_authTitle"> Login
    </h3>
    <div class="row omb_row-sm-offset-3 omb_socialButtons">
      <div class="col-xs-4 col-sm-2">
        <a href="#" class="btn btn-lg btn-block omb_btn-facebook">
          <i class="fa fa-facebook visible-xs"></i>
          <span class="hidden-xs">Facebook</span>
        </a>
      </div>
      <div class="col-xs-4 col-sm-2">
        <a href="#" class="btn btn-lg btn-block omb_btn-twitter">
          <i class="fa fa-twitter visible-xs"></i>
          <span class="hidden-xs">Twitter</span>
        </a>
      </div>
      <div class="col-xs-4 col-sm-2">
        <a href="#" class="btn btn-lg btn-block omb_btn-google">
          <i class="fa fa-google-plus visible-xs"></i>
          <span class="hidden-xs">Google+</span>
        </a>
      </div>
    </div>
    <!-- Begin of login page -->
    <div class="row omb_row-sm-offset-3 omb_loginOr">
      <div class="col-xs-12 col-sm-6">
        <hr class="omb_hrOr">
        <span class="omb_spanOr">or</span>
      </div>
    </div>

    <div class="row omb_row-sm-offset-3">
      <div class="col-xs-12 col-sm-6">
      <%= form_tag(sessions_path, :class => "omb_loginForm") do%>
        <div class="input-group">
          <span class="input-group-addon">
            <i class="fa fa-user"></i>
          </span>
          <%= email_field_tag :email, "",class: "form-control", :placeholder => "Email Address" %>
        </div>
        <span class="help-block"></span>

        <div class="input-group">
          <span class="input-group-addon">
            <i class="fa fa-lock"></i>
          </span>
          <%= password_field_tag :password, "", class: "form-control", placeholder: "Password" %>
        </div>
        <br>
        <!-- <span class="help-block">Password error</span> -->
        <label style="font-size:20px; border:solid; background:lightgrey; text-align: center;" class="checkbox text-bold">
          <%= check_box_tag(:admin) %>
          <b><%= label_tag :admin, "Admin!" %></b>
        </label>
        <%= submit_tag "Login",id: "button", class: "btn btn-lg btn-primary btn-block" %>

    </div>
  </div>

  <div class="row omb_row-sm-offset-3">

  <% end  %>
</div>

</div>

app/views/partials/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top " role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">

      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand navbar-nav" href="<%= root_path %>">Property Pal</a>
    </div>

    <div class="collapse navbar-collapse" id="myNavbar">

      <ul class="nav navbar-nav">

            <% if tenant_logged_in? %>
              <li><a href="<%= tenant_dashboard_url %>"></a></li>
            <% elsif admin_logged_in? %>
              <a href="<%= admin_dashboard_url %>"></a></li>
            <% else %>
              <li class="active"><a href="<%= root_path %>">Home</a> </li>
            <% end %>

          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Jump To
              <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li> <%=link_to "Properties", properties_path%></li>
              <li> <%=link_to "Sectors", sectors_path%></li>
              <li> <%=link_to "Units", units_path%> </li>
            </ul>
          </li>

          <li><a href="#">Contact</a></li>
          <li><%= link_to "About Us", about_path %></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
            <% if tenant_logged_in? %>
            <li class="active">  <a href="<%= tenant_dashboard_url %>">Dashboard</a> </li>
            <% elsif admin_logged_in? %>
            <li class="active">  <a href="<%= admin_dashboard_url %>">Dashboard</a> </li>
            <% else %>
            <li>
            <a href="<%= login_path %>">
              <span class="glyphicon glyphicon-log-in"></span>
              Login</a></li>
            <% end  %>
          <li>
            <% if tenant_logged_in? ||  admin_logged_in?%>
              <a href="<%= logout_path %>"><span class="glyphicon glyphicon-log-out"></span> Logout </a>
              <% else %>
              <a href="<%= new_tenant_path %>">
                <span class="glyphicon glyphicon-user"></span>
                Sign-Up</a>
                <% end %>
          </li>
        </ul>
      </div>
    </div>

  </nav>

app/views/partials/_navigation_test.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top " role="navigation">
  <div class="container-fluid">
      <div class="navbar-header">

        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand navbar-nav" href="<%= admin_dashboard_path %>">(a_a)</a>
      </div>

      <div class="collapse navbar-collapse" id="myNavbar">

        <ul class="nav navbar-nav">
          <li class="active"><a href="#">Home</a></li>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Page 1 <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">Page 1-1</a></li>
              <li><a href="#">Page 1-2</a></li>
              <li><a href="#">Page 1-3</a></li>
            </ul>
          </li>
          <li><a href="#">Page 2</a></li>
          <li><a href="#">Page 3</a></li>
        </ul>


      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><span class="glyphicon glyphicon-user"></span> Profile</a></li>
        <li>
          <% if admin_logged_in? %>
          <a href="<%= logout_path %>"><span class="glyphicon glyphicon-log-in"></span> Logout</a>
          <% else %>
          <a href="<%= logout_path %>"><span class="glyphicon glyphicon-log-in"></span>Login</a>
          <% end %></li>
      </ul>
    </div>
  </div>

</nav>